# Generated by Django 4.0.6 on 2023-04-17 07:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_camera'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
